apiVersion: v1
kind: Service
metadata:
  name: {{ include "papercrate.fullname" . }}-backend
  labels:
    {{- include "papercrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "papercrate.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
