{{- if not .Values.backend.env.existingSecret }}
{{- $jwt := required "backend.env.jwtSecret must be provided when auto-creating secret" .Values.backend.env.jwtSecret -}}
{{- $config := dict "databaseUrl" .Values.backend.env.databaseUrl -}}
{{- if not (index $config "databaseUrl") -}}
  {{- if .Values.postgres.enabled -}}
    {{- $dbUser := required "postgres.auth.username is required when postgres.enabled" .Values.postgres.auth.username -}}
    {{- $dbPass := required "postgres.auth.password is required when postgres.enabled" .Values.postgres.auth.password -}}
    {{- $dbName := default "papercrate" .Values.backend.env.databaseName -}}
    {{- $dbHost := printf "%s-postgres" (include "papercrate.fullname" .) -}}
    {{- $_ := set $config "databaseUrl" (printf "postgres://%s:%s@%s:5432/%s" $dbUser $dbPass $dbHost $dbName) -}}
  {{- else -}}
    {{- fail "backend.env.databaseUrl must be provided when postgres.enabled is false" -}}
  {{- end -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "papercrate.fullname" . }}-backend-env
  labels:
    {{- include "papercrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
stringData:
  JWT_SECRET: {{ $jwt | quote }}
  DATABASE_URL: {{ index $config "databaseUrl" | quote }}
{{- end }}
